realsense_explorer:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: long_u_joint
    pid: {p: 15, i: 0.1, d: 0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: mid_link_joint
    pid: {p: 15, i: 0.1, d: 0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: camera_mount_joint
    pid: {p: 15, i: 0.1, d: 0}

  # Trs base Controller-----------------------------------------
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: left_wheel_joint
    right_wheel: right_wheel_joint
    wheel_separation: 0.2
    wheel_radius: 0.055
    cmd_vel_timeout: 0.25
    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    base_frame_id: base_link

/gazebo_ros_control:
  pid_gains:
    right_wheel_joint:
      p: 1000.0
      i: 0.01
      d: 10.0
    left_wheel_joint:
      p: 1000.0
      i: 0.01
      d: 10.0